name       : libetonyek
version    : 0.1.6
release    : 1
source     :
    - http://dev-www.libreoffice.org/src/libetonyek/libetonyek-0.1.6.tar.xz : df54271492070fbcc6aad9f81ca89658b25dd106cc4ab6b04b067b7a43dcc078
license    : MPL-2.0
component  : programming
summary    : Library and a set of tools for reading and converting Apple iWork documents
description: |
    Library and a set of tools for reading and converting Apple iWork documents.
builddeps  :
    - pkgconfig(cppunit)
    - pkgconfig(glm)
    - pkgconfig(liblangtag)
    - pkgconfig(librevenge-stream-0.0)
    - libboost-devel
    - pkgconfig(mdds-1.2)
setup      : |
    %patch -p1 < $pkgfiles/Allow-building-with-mdds-1.2.patch
    %autogen --with-mdds="1.2"
build      : |
    %make
install    : |
    %make_install
