name       : libetonyek
version    : 0.1.10
release    : 6
source     :
    - https://dev-www.libreoffice.org/src/libetonyek/libetonyek-0.1.10.tar.xz : b430435a6e8487888b761dc848b7981626eb814884963ffe25eb26a139301e9a
license    : MPL-2.0
component  : programming
summary    : Library and a set of tools for reading and converting Apple iWork documents
description: |
    Library and a set of tools for reading and converting Apple iWork documents.
builddeps  :
    - pkgconfig(cppunit)
    - pkgconfig(glm)
    - pkgconfig(liblangtag)
    - pkgconfig(librevenge-0.0)
    - pkgconfig(mdds-2.1)
    - libboost-devel
setup      : |
    %configure --with-mdds=2.1
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
