name       : libetonyek
version    : 0.1.8
release    : 3
source     :
    - https://dev-www.libreoffice.org/src/libetonyek/libetonyek-0.1.8.tar.xz : 9dc92347aee0cc9ed57b175a3e21f9d96ebe55d30fecb10e841d1050794ed82d
license    : MPL-2.0
component  : programming
summary    : Library and a set of tools for reading and converting Apple iWork documents
description: |
    Library and a set of tools for reading and converting Apple iWork documents.
builddeps  :
    - pkgconfig(cppunit)
    - pkgconfig(glm)
    - pkgconfig(liblangtag)
    - pkgconfig(librevenge-0.0)
    - pkgconfig(mdds-1.2)
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
